name: 'Setup Go and OpenAPI'
description: 'Sets up Go environment with caching and generates OpenAPI code'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: "**/go.sum"

    - name: Cache Go build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-

    - name: Generate OpenAPI code
      run: make openapi
      shell: bash
