version: "2"
run:
  tests: true
  allow-parallel-runners: true

linters:
  default: "none"
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - errorlint
    - gocritic
    - godox
    - gosec
    - loggercheck
    - nilerr
    - reassign
    - recvcheck
    - revive
    - sloglint
    - testifylint
    - unconvert
    - durationcheck
    - errname
    - gocheckcompilerdirectives
    - makezero
    - nilnesserr
    - nilnil
    - predeclared
    - wastedassign
    - errchkjson
    - perfsprint
    - usestdlibvars
    - usetesting
    - contextcheck
    - fatcontext
    - noctx
    - copyloopvar
    - intrange
    - modernize
    - prealloc
    - misspell
    - nakedret
    - nolintlint
    - thelper
    - tparallel
    - unparam
    - whitespace

  settings:
    godox:
      keywords:
        - TODO
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation: []
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true

  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - gen$
    rules:
      - path: integrationtests/
        linters:
          - perfsprint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/henok321/knobel-manager-service)
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: strict
    paths:
      - third_party$
      - builtin$
      - examples$
      - gen$
