# fly.toml app configuration file generated for knobel-manager-service on 2024-10-07T18:24:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knobel-manager-service'
primary_region = 'ams'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[metrics]
path = "/metrics"
port = 9090
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "15s"
timeout = "5s"
method = "GET"
path = "/health/ready"

[[vm]]
size = 'shared-cpu-1x'
