# fly.toml app configuration file generated for knobel-manager-service on 2024-10-06T03:57:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knobel-manager-service'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
