openapi: 3.0.0
info:
  title: Knobel Manager Service API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health Check
      operationId: healthCheck
      security: [ ]
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
  /games:
    get:
      summary: Get Games
      operationId: getGames
      security:
        - firebaseAuth: [ ]
      responses:
        '200':
          description: List of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
    post:
      summary: Create Game
      operationId: createGame
      security:
        - firebaseAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '201':
          description: Game created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /games/{id}:
    get:
      summary: Get Game by ID
      operationId: getGameById
      security:
        - firebaseAuth: [ ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Game details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Game not found
    put:
      summary: Update Game
      operationId: updateGame
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: Game updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
    delete:
      summary: Delete Game
      operationId: deleteGame
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Game deleted
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        owner:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    firebaseAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://knobel-manager-webapp.firebaseapp.com/login"
          scopes: {}
      scheme: bearer
      bearerFormat: JWT
      x-google-issuer: "https://securetoken.google.com/knobel-manager-webapp"
      x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
      x-google-audiences: "knobel-manager-webapp"
      description: |
        Firebase Authentication is used to secure this API. Clients must provide a valid Firebase ID token in the `Authorization` header.
security:
  - firebaseAuth: []