-- +goose Up

-- Add soft delete columns to all tables

ALTER TABLE GAMES ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE GAMES ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE GAMES ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE GAMES ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE teams ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE teams ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE teams ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE teams ADD CONSTRAINT unique_team UNIQUE (id);

ALTER TABLE players ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE players ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE players ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE players ADD CONSTRAINT unique_player UNIQUE (id);

ALTER TABLE rounds ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE rounds ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE rounds ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE rounds ADD CONSTRAINT unique_round UNIQUE (id);

ALTER TABLE game_tables ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE game_tables ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE game_tables ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE game_tables ADD CONSTRAINT unique_game_table UNIQUE (id);

ALTER TABLE scores ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE scores ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE scores ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE scores ADD CONSTRAINT unique_score UNIQUE (id);