-- +goose Up

-- Add soft delete columns to all tables

ALTER TABLE GAMES ALTER COLUMN CREATED_AT DROP DEFAULT;
ALTER TABLE GAMES ALTER COLUMN CREATED_AT DROP NOT NULL;
ALTER TABLE GAMES ALTER COLUMN UPDATED_AT DROP DEFAULT;
ALTER TABLE GAMES ALTER COLUMN UPDATED_AT DROP NOT NULL;

ALTER TABLE TEAMS ADD COLUMN CREATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE TEAMS ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE TEAMS ADD COLUMN DELETED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE TEAMS ADD CONSTRAINT UNIQUE_TEAM UNIQUE (ID);

ALTER TABLE PLAYERS ADD COLUMN CREATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE PLAYERS ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE PLAYERS ADD COLUMN DELETED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE PLAYERS ADD CONSTRAINT UNIQUE_PLAYER UNIQUE (ID);

ALTER TABLE ROUNDS ADD COLUMN CREATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE ROUNDS ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE ROUNDS ADD COLUMN DELETED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE ROUNDS ADD CONSTRAINT UNIQUE_ROUND UNIQUE (ID);

ALTER TABLE GAME_TABLES ADD COLUMN CREATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_TABLES ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_TABLES ADD COLUMN DELETED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE GAME_TABLES ADD CONSTRAINT UNIQUE_GAME_TABLE UNIQUE (ID);

ALTER TABLE SCORES ADD COLUMN CREATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE SCORES ADD COLUMN UPDATED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE SCORES ADD COLUMN DELETED_AT TIMESTAMP WITH TIME ZONE;
ALTER TABLE SCORES ADD CONSTRAINT UNIQUE_SCORE UNIQUE (ID);
