-- +goose Up

DROP INDEX IF EXISTS idx_games_deleted_at;
ALTER TABLE games
DROP CONSTRAINT IF EXISTS games_id_deleted_at_key;
ALTER TABLE games
DROP COLUMN IF EXISTS deleted_at;

ALTER TABLE games
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE games
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE games
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE games
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE teams
DROP CONSTRAINT IF EXISTS unique_team;
ALTER TABLE teams
DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE teams
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE teams
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE teams
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE teams
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE players
DROP CONSTRAINT IF EXISTS unique_player;
ALTER TABLE players
DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE players
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE players
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE players
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE players
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE rounds
DROP CONSTRAINT IF EXISTS unique_round;
ALTER TABLE rounds
DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE rounds
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE rounds
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE rounds
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE rounds
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE game_tables
DROP CONSTRAINT IF EXISTS unique_game_table;
ALTER TABLE game_tables
DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE game_tables
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE game_tables
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE game_tables
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE game_tables
ALTER COLUMN updated_at SET DEFAULT NOW();

ALTER TABLE scores
DROP CONSTRAINT IF EXISTS unique_score;
ALTER TABLE scores
DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE scores
ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE scores
ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE scores
ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE scores
ALTER COLUMN updated_at SET DEFAULT NOW();
