name: SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".pre-commit-config.yaml"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".pre-commit-config.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go and OpenAPI
        uses: ./.github/actions/setup-go-openapi

      - name: Run tests, generate coverage and report files
        run: go test ./... -coverpkg=./... -coverprofile=coverage.out --json > test-report.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: "--timeout 5m --out-format=checkstyle:golangci-lint-report.xml"

      - name: Analyze project and upload coverage
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
