name: SonarCloud

on:
  workflow_dispatch:

jobs:
  sonarcloud:
      name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}