name: SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignored:
      - 'README.md'
      - 'LICENSE'
      - '.pre-commit-config.yaml'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests, generate coverage and report files
        run: go test ./... -coverprofile=coverage.out --json > test-report.json

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Run golangci-lint and generate report
        run: golangci-lint run --timeout 5m --out-format checkstyle > golangci-lint-report.xml

      - name: Analyze project and upload coverage
        uses: sonarsource/sonarcloud-github-action@v4
        with:
          args: >
            -Dsonar.projectKey=henok321_knobel-manager-service
            -Dsonar.organization=henok321
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.xml
            -Dsonar.go.tests.reportPaths=test-report.json
            -Dsonar.coverage.exclusions=**/integration_tests/**,**/cmd/**,**/*_test.go
            -Dsonar.cpd.exclusions=**/integration_tests/**,**/cmd/**,**/*_test.go

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
